# comment
SOURCES = Animal Robot RobotMonkey


Animal:
	g++ -o animal AnimalUsage.cpp AnimalObject.cpp EnemyObject.cpp MonkeyObject.cpp

Robot:
	g++ -o robot RobotTest.cpp RobotObject.cpp

RobotMonkey:
	g++ -o robotmonkey RobotMonkeyTest.cpp AnimalObject.cpp MonkeyObject.cpp RobotObject.cpp RobotMonkeyObject.cpp
