/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "msg.h"

bool_t
xdr_ldata (XDR *xdrs, ldata *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->val))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	return TRUE;
}
