
all: vector simplevector

simplevector:
	g++ -o simplevector simplevector.cpp
vector:
	g++ -o vector vector.cpp

object:
	g++ objectvector.cpp ../GenericObjects/AnimalObject.cpp 

clean:
	rm -f *.o
	rm -f vector simplevector
